name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g textlint
      - run: npm install -g textlint-plugin-review \
        textlint-rule-prh \
        textlint-rule-preset-ja-technical-writing \
        textlint-rule-preset-ja-spacing \
        textlint-filter-rule-comments
      - run: cd textlint && \
        textlint ../contents/*.re

